#!/usr/bin/env nbb
;; Regenerate lang/package-conformance/signature-vectors.edn.
;;
;; These are golden vectors, not fixtures a test regenerates for itself. Both
;; runtimes read the SAME committed bytes and must reach the same verdict on
;; each one; a test that signed its own message would agree with itself on a
;; host whose signing and verification were both wrong.
;;
;;   nbb --classpath <org-ietf-ed25519>/src scripts/gen-signature-vectors.cljs \
;;     > lang/package-conformance/signature-vectors.edn
;;
;; Seeds are fixed constants: the point is a stable corpus, not entropy. No
;; private key here guards anything -- the seeds are in this file.

(ns gen-signature-vectors
  (:require [ed25519.core :as ed]))

(defn- seed [b] (js/Uint8Array.from (clj->js (vec (repeat 32 b)))))
(defn- b64 [u8] (.toString (js/Buffer.from u8) "base64"))

(def ^:private signer (seed 11))
(def ^:private other (seed 22))
(def ^:private did (ed/did-key-from-pub (ed/pubkey-from-seed signer)))
(def ^:private other-did (ed/did-key-from-pub (ed/pubkey-from-seed other)))

;; The message a package signature attests to is the manifest's own declared
;; :manifest-cid -- see `kotoba.lang.package-contract/signatures-error`. This
;; is the real CID from lang/package-conformance/positive/package-manifest.edn.
(def ^:private manifest-cid
  "bafyreia4kejp3eqgyv3fbb6yrxkzemeqehopntqntvgkcq7maqltxrh57q")
(def ^:private other-cid
  "bafyreigyygk6epd5ge2akwuafpdjmztjc27v5pr7wpqnq37re7xhjwxsl4")

(def ^:private msg (.encode (js/TextEncoder.) manifest-cid))
(def ^:private valid (ed/sign signer msg))

(def ^:private tampered
  ;; One flipped bit of a real signature: the shape is right, the bytes are not.
  (let [c (js/Uint8Array.from valid)]
    (aset c 0 (bit-xor (aget c 0) 1))
    c))

(println
 (str "{:kotoba.lang.package.signature-vectors/version 1\n"
      " :note \"Generated by scripts/gen-signature-vectors.cljs -- do not hand-edit.\"\n"
      " :manifest-cid " (pr-str manifest-cid) "\n"
      " :signer-did " (pr-str did) "\n"
      " :other-did " (pr-str other-did) "\n"
      " :valid-sig " (pr-str (b64 valid)) "\n"
      " :tampered-sig " (pr-str (b64 tampered)) "\n"
      " :wrong-key-sig " (pr-str (b64 (ed/sign other msg))) "\n"
      " :other-message-sig "
      (pr-str (b64 (ed/sign signer (.encode (js/TextEncoder.) other-cid)))) "\n"
      " :not-base64-sig \"!!!not base64!!!\"}"))
